### ISSUE TITLE
Token changing in the server

### ISSUE THREAD

**Issue by Adirio** [coap-technology/coap-technology.github.io#16]
When a client sends a confirmable request with an empty token, the server should send the piggybacked acknowledgement with an empty token as specified in 5.3.2:

> 2.  In a piggybacked response, the Message ID of the Confirmable
       request and the Acknowledgement MUST match, and the tokens of the
       response and original request MUST match.  In a separate
       response, just the tokens of the response and original request
       MUST match.

Is a server allowed to change the token on a non-piggybacked acknowledgment? I think this needs to be defined in the specification. Only piggybacked and separate responses are specified in the previous cite.

**Comment by cabo** [comment]
Hi Adirio,

a non-piggybacked ACK is an empty message:

```
   Empty Message
      A message with a Code of 0.00; neither a request nor a response.
      An Empty message only contains the 4-byte header.
```

So there is no token in that ACK (its only identifier is the message-ID), and the question is moot.

(Conversely, an ACK with a TKL ≠ 0 is not an empty message and thus cannot serve as a non-piggybacked ACK.)

**Comment by Adirio** [comment]
True, so servers always need to leave the token equal to the one the client sent. I was just confirming that this applied to every kind of response as I found a server implementation that does not handle this correctly, as explained in #17.
